### ISSUE TITLE
API change adjustItemQuantity --> adjustOrderLine

### ISSUE THREAD

**Issue by ramezrafla** [vendure-ecommerce/gatsby-storefront#1]
This example still works well and ticking, there is one API change we noticed in `ShoppingCart.vendure.ts`
With that fixed we didn't notice any further problems

Maybe update `package.json` to point to newer libs?
Happy to PR

**Comment by michaelbromley** [comment]
Hi,
Sure, this project was basically entirely written over a 2 day pair-programming session with a friend of mine who knows React much better than I do. Since then I've not worked on it, so I'm actually surprised it still more-or-less works!

I would _love_ to accept whatever work you are willing to do to bring this up-to-date, with current versions of the dependencies and any other features you'd like to add (I think it would be nice to have a Gatsby example comparable to https://demo.vendure.io/storefront, but I realise you might not have time to do all that work).

I can give you write-access to this repo if you like, let me know.

**Comment by ramezrafla** [comment]
Thanks @michaelbromley,

I am happy to take on the Gatsby side of things, if you don't mind giving me write access I can:
- Step 1: Update this repo with latest versions (and changes) 
- Step 2: Once it's completed, I'll push the Gatsby framework we will use for our store, maybe we can even add it to the formal Gatsby starter-packs, will increase number of users (and add to marketing by tapping in to the Gastby community). As of yet, I didn't see any starter themes for open-source eCommerce solutions

**Comment by michaelbromley** [comment]
I just invited you to write to this repo. The plans sound good! I think promoting Vendure more broadly to the Gatsby community would be very good for our profile, and it's a great match for devs already familiar with the JS/Node world.

**Comment by ramezrafla** [comment]
I agree, combined with a Medium article (and maybe conversation with the Gatsby folks), could result in major uptick in use. Are we on track for v1 to be released out of beta soon? That will help adoption.

**Comment by michaelbromley** [comment]
I'm hoping for around the end of the year for v1.0. I'd like there to be maybe 1 or 2 more minor releases (so, v0.17.0, 0.18.0) and then proceed to release candidates of v1.0.

**Comment by ramezrafla** [comment]
Excellent! Thanks so much
